/**
 * Hanwha Eagles Game Day - Daejeon Local Travel Guide Data
 * Authentic venues, coordinates, travel times from Hanwha Life Eagles Park (36.3172, 127.4291)
 */

const APP_DATA = {
  stadium: {
    name_en: "Hanwha Life Eagles Park",
    name_kr: "한화생명 이글스파크",
    address_en: "373 Daejong-ro, Jung-gu, Daejeon",
    address_kr: "대전광역시 중구 대종로 373 (부사동)",
    lat: 36.3172,
    lng: 127.4291,
    capacity: "13,000 seats",
    opened: "1964 (Renovated)",
    new_stadium_info: "Baseball Dream Park (opening next door in 2025/2026)",
    cheer_zone: "1st Base Orange Cheer Zone (Blocks 101-106)",
    famous_snacks: [
      { name: "Bori Tteokbokki (보리떡볶이)", desc: "Legendary stadium snack stall with spicy rice cakes & fried mandu", price: "₩4,500" },
      { name: "Nongshim Eagles Fried Chicken", desc: "Crispy whole chicken delivered hot to your seat", price: "₩19,000" },
      { name: "Stir-fried Sundae (순대볶음)", desc: "Spicy glass noodle blood sausage stir-fry", price: "₩7,000" },
      { name: "Frozen Slush Draft Beer", desc: "Ice-capped draft beer in souvenir Eagles cup", price: "₩5,000" }
    ]
  },

  match_info: {
    opponent: "SSG Landers",
    opponent_kr: "SSG 랜더스",
    date: "Today's Game",
    time: "18:30 KST",
    stadium: "Hanwha Life Eagles Park (Home)",
    home_starter: "Ryu Hyun-jin (#99)",
    weather: "24°C Sunny, Gentle Breeze 🍃",
    gates_open: "16:30 (2 hours before game)",
    broadcast: "SBS Sports / SPOTV / TVING"
  },

  categories: [
    { id: "before_game", icon: "⚾", name_en: "Before the Game", name_kr: "경기 전 코스", desc_en: "Quick eats, photo spots & team goods near the park", desc_kr: "야구장 주변 맛집, 굿즈샵, 사진 명소" },
    { id: "restaurants", icon: "🍜", name_en: "Best Restaurants", name_kr: "대전 찐 맛집", desc_en: "Legendary Kalguksu, spicy Duruchigi & Hanwoo BBQ", desc_kr: "칼국수 성지, 두루치기, 한우 숯불갈비" },
    { id: "cafes", icon: "☕", name_en: "Cafes & Desserts", name_kr: "카페 & 디저트", desc_en: "Sung Sim Dang pilgrimage & aesthetic hanok cafes", desc_kr: "성심당 빵지순례, 대흥동 감성 한옥 카페" },
    { id: "attractions", icon: "📸", name_en: "Nearby Attractions", name_kr: "주변 명소", desc_en: "Skyroad, Bomunsan Observatory & Hanbit Tower", desc_kr: "스카이로드, 보문산 전망대, 한빛탑" },
    { id: "family", icon: "👨‍👩‍👧", name_en: "Family Friendly", name_kr: "가족 추천 코스", desc_en: "Kid-friendly eateries, theme parks & green parks", desc_kr: "아이와 함께 가기 좋은 오월드, 엑스포공원" },
    { id: "after_game", icon: "🌙", name_en: "After the Game", name_kr: "경기 후 뒤풀이", desc_en: "Night pocha, craft beer & victory celebrations", desc_kr: "중앙시장 야시장, 대흥동 수제맥주 & 포차" },
    { id: "station", icon: "🚉", name_en: "Daejeon Station", name_kr: "대전역 연계", desc_en: "Express routes, lockers & souvenirs near KTX station", desc_kr: "KTX 대전역 짐보관, 성심당 대전역점, 빠른 이동" },
    { id: "eagles_park", icon: "🏟️", name_en: "Eagles Park Tips", name_kr: "이글스파크 꿀팁", desc_en: "Gate guides, cheering songs, best food & parking", desc_kr: "응원존 좌석 팁, 구장 명물 먹거리, 주차 팁" }
  ],

  time_plans: [
    {
      id: "1hr",
      duration_en: "1 HOUR",
      duration_kr: "1시간 코스",
      subtitle_en: "Quick Coffee & Stadium Photo Walk",
      subtitle_kr: "빠른 커피 한잔 & 이글스 굿즈샵 포토스팟",
      vibe: "⚡ Express Game Day",
      budget: "₩10,000 - ₩18,000",
      description_en: "Perfect if you arrived right before gates open. Grab an iced signature coffee in Daeheung-dong, pick up your orange cheering sticks at the official shop, and take a selfie at the Eagles Wall.",
      description_kr: "경기 시작 직전 도착했을 때 추천! 대흥동 감성 카페에서 시원한 테이크아웃 커피를 들고 이글스 공식 샵에서 주황색 응원봉 구매 후 포토존 인증샷!",
      steps: [
        { time: "45 min before", name_en: "Sung Sim Dang Boutique or Local Cafe", name_kr: "성심당 케익부띠끄 / 대흥동 카페", icon: "☕", type: "cafe" },
        { time: "20 min before", name_en: "Hanwha Eagles Official Goods Shop", name_kr: "한화이글스 공식 굿즈샵 (유니폼 & 응원도구)", icon: "🧢", type: "shop" },
        { time: "10 min before", name_en: "1st Base Gate Entrance & Snack Pickup", name_kr: "1루 출입구 입장 및 보리떡볶이 픽업", icon: "🏟️", type: "stadium" }
      ]
    },
    {
      id: "2hr",
      duration_en: "2 HOURS",
      duration_kr: "2시간 코스",
      subtitle_en: "Local Daejeon Feast + Dessert Break",
      subtitle_kr: "대전 대표 칼국수/두루치기 든든한 식사 + 디저트",
      vibe: "🍜 Foodie Pre-Game",
      budget: "₩20,000 - ₩35,000",
      description_en: "Plenty of time to savor Daejeon's famous spicy squid duruchigi or deep-broth kalguksu in nearby Daeheung-dong, followed by a quick pastry stop before heading into the park.",
      description_kr: "야구장 도보/차량 5분 거리 대흥동에서 매콤한 오징어 두루치기나 칼국수로 든든하게 배를 채우고, 성심당 튀김소보로 픽업 후 여유롭게 야구장 도착!",
      steps: [
        { time: "120 min before", name_en: "Gwangcheon Sikdang (Spicy Squid Duruchigi)", name_kr: "광천식당 (오징어두루치기 + 면사리)", icon: "🍚", type: "food" },
        { time: "50 min before", name_en: "Cafe Sosorowa Hanok Cafe", name_kr: "카페 소소로와 (수제 디저트 & 에이드)", icon: "🍰", type: "cafe" },
        { time: "20 min before", name_en: "Arrive at Eagles Park, Enjoy Warm-up Practice", name_kr: "이글스파크 도착 & 선수단 타격훈련 관람", icon: "⚾", type: "stadium" }
      ]
    },
    {
      id: "3-4hr",
      duration_en: "3–4 HOURS",
      duration_kr: "3~4시간 코스",
      subtitle_en: "Attraction + Legendary Bakery + Stadium Walk",
      subtitle_kr: "보문산 전망대/스카이로드 + 성심당 본점 + 야구장",
      vibe: "🌟 Classic Daejeon Tour",
      budget: "₩30,000 - ₩50,000",
      description_en: "The gold standard Daejeon baseball pilgrimage: Explore Eunhaeng-dong Skyroad, conquer Sung Sim Dang main bakery, enjoy panoramic views from Bomunsan Mountain or Expo Park, then march to the stadium.",
      description_kr: "가장 인기 있는 대전 야구 당일치기 코스! 으능정이 스카이로드 구경 후 성심당 본점 빵지순례, 보문산 전망대에서 대전 시내 전경을 내려다보고 야구장 직행!",
      steps: [
        { time: "3.5 hrs before", name_en: "Eunhaeng-dong Skyroad & Cultural Street", name_kr: "으능정이 문화의거리 & 스카이로드", icon: "📸", type: "spot" },
        { time: "2.5 hrs before", name_en: "Sung Sim Dang Main Bakery Tour", name_kr: "성심당 본점 빵지순례 (튀김소보로 & 부추빵)", icon: "🥐", type: "cafe" },
        { time: "1.5 hrs before", name_en: "Shindo Kalguksu / Jinro-jip Tofu Feast", name_kr: "신도칼국수 / 진로집 두부두루치기", icon: "🍜", type: "food" },
        { time: "40 min before", name_en: "Bomunsan Forest View & Eagles Park Entry", name_kr: "보문산 전망대 산책 후 이글스파크 입장", icon: "🏟️", type: "stadium" }
      ]
    },
    {
      id: "allday",
      duration_en: "ALL DAY",
      duration_kr: "올데이 풀코스",
      subtitle_en: "Ultimate KTX Daejeon Baseball & City Adventure",
      subtitle_kr: "KTX 대전역 도착부터 밤풀이까지 완벽한 풀코스",
      vibe: "🚀 The Complete Experience",
      budget: "₩50,000 - ₩90,000",
      description_en: "Arrive at Daejeon Station by KTX, visit Hanbit Tower & Expo Park or PPuri Park, indulge in a 3-stop food & dessert marathon, cheer your lungs out at Eagles Park, and celebrate at Jungang Market pocha.",
      description_kr: "KTX 대전역 도착 후 엑스포 한빛탑 or 오월드/뿌리공원 나들이, 대전 3대 맛집 정복, 열정적인 1루 오렌지 응원전, 경기 후 중앙시장 야시장 뒤풀이까지!",
      steps: [
        { time: "11:00 AM", name_en: "Arrive at Daejeon Station (Lockers & KTX Snack)", name_kr: "KTX 대전역 도착 (짐보관 & 가벼운 시작)", icon: "🚉", type: "station" },
        { time: "12:00 PM", name_en: "Hanbit Tower & Expo Science Park Music Fountain", name_kr: "엑스포 과학공원 & 한빛탑 미디어파사드", icon: "🗼", type: "spot" },
        { time: "02:00 PM", name_en: "Lunch: 60-Year Shindo Kalguksu or Wanggwan Sikdang", name_kr: "점심: 60년 전통 신도칼국수 or 왕관식당 육회콩나물밥", icon: "🍜", type: "food" },
        { time: "03:30 PM", name_en: "Sung Sim Dang Cake Boutique & Daeheung Cafe Street", name_kr: "성심당 케익부띠끄 & 대흥동 카페거리", icon: "☕", type: "cafe" },
        { time: "05:00 PM", name_en: "Enter Eagles Park, Official Merch & Seat Setup", name_kr: "이글스파크 1루 입장, 굿즈 장착 & 치맥 세팅", icon: "⚾", type: "stadium" },
        { time: "06:30 PM", name_en: "Game Time! Hanwha Eagles Victory Cheering", name_kr: "플레이볼! 승리를 향한 열정 응원전", icon: "🔥", type: "stadium" },
        { time: "10:00 PM", name_en: "Victory Party: Jungang Market Night Pocha Alley", name_kr: "승리의 뒤풀이: 중앙시장 야시장 포차 골목", icon: "🌙", type: "night" }
      ]
    }
  ],

  restaurants: [
    {
      id: "gwangcheon",
      name_en: "Gwangcheon Sikdang",
      name_kr: "광천식당",
      category: "local",
      category_label_en: "Spicy Duruchigi",
      category_label_kr: "오징어/두부 두루치기",
      price: "₩14,000 - ₩22,000",
      rating: 4.8,
      reviews_count: 3420,
      distance_km: "1.4 km",
      travel_walk: "18 min",
      travel_taxi: "4 min (₩4,500)",
      travel_bus: "8 min (Bus #802 / #2)",
      recommended_for: ["Young fans", "Couples", "Spicy food lovers"],
      recommended_for_kr: ["젊은 팬", "커플", "매운맛 마니아"],
      hours_en: "10:30 AM - 09:30 PM (Closed Mondays)",
      hours_kr: "10:30 ~ 21:30 (매주 월요일 휴무)",
      signature_en: "Spicy Squid Duruchigi (오징어두루치기), Kalguksu Noodle Extra (면사리), Suyuk (수육)",
      signature_kr: "오징어 두루치기, 양념 면사리, 부드러운 수육",
      lat: 36.3262,
      lng: 127.4278,
      address_en: "12 Daejong-ro 505beon-gil, Jung-gu, Daejeon",
      address_kr: "대전 중구 대종로505번길 12 (선화동)",
      image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
      description_en: "A legendary 45-year Daejeon institution featured on Baek Jong-won's 3 Kings. Its fiery, deeply flavorful squid duruchigi mixed with springy kalguksu noodles is an absolute must-try before any baseball match!",
      description_kr: "백종원의 3대천왕에 방영된 45년 전통 대전의 전설적인 맛집. 중독성 강한 매콤칼칼한 오징어 두루치기에 쫄깃한 면사리를 비벼먹으면 야구 응원 전 완벽한 에너지 충전 완료!",
      tags: ["🔥 Hot & Spicy", "📺 TV Featured", "🍜 Legend"]
    },
    {
      id: "shindo",
      name_en: "Shindo Kalguksu",
      name_kr: "신도칼국수 본점",
      category: "noodles",
      category_label_en: "Kalguksu Noodles",
      category_label_kr: "전통 칼국수",
      price: "₩6,000 - ₩18,000",
      rating: 4.7,
      reviews_count: 2890,
      distance_km: "1.8 km",
      travel_walk: "24 min",
      travel_taxi: "5 min (₩4,800)",
      travel_bus: "11 min (Bus #2)",
      recommended_for: ["Families", "All Ages", "Comfort food"],
      recommended_for_kr: ["가족", "전 연령", "든든한 한끼"],
      hours_en: "09:30 AM - 08:30 PM (Daily)",
      hours_kr: "09:30 ~ 20:30 (연중무휴)",
      signature_en: "Perilla Seed Anchovy Kalguksu (들깨칼국수), Boiled Pork Suyuk (수육)",
      signature_kr: "고소한 들깨칼국수, 부드러운 암뽕/수육",
      lat: 36.3298,
      lng: 127.4332,
      address_en: "2 Daejeon-ro 825beon-gil, Dong-gu, Daejeon",
      address_kr: "대전 동구 대전로825번길 2 (정동, 대전역 앞)",
      image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
      description_en: "Founded in 1961, Shindo is the mother of Daejeon's famous Kalguksu culture. The deep anchovy and beef bone broth dusted with aromatic perilla seed powder warms the soul. Incredibly affordable and authentic.",
      description_kr: "1961년부터 대전 칼국수의 역사를 써내려온 3대 전통 맛집. 멸치와 사골로 우려낸 진하고 구수한 육수에 고소한 들깨가루가 어우러져 남녀노소 모두가 감탄하는 맛!",
      tags: ["🏆 60yr Heritage", "🥣 Deep Broth", "💰 Great Value"]
    },
    {
      id: "jinrojip",
      name_en: "Jinro-jip",
      name_kr: "진로집",
      category: "local",
      category_label_en: "Tofu Duruchigi",
      category_label_kr: "50년 전통 두부두루치기",
      price: "₩12,000 - ₩24,000",
      rating: 4.6,
      reviews_count: 4100,
      distance_km: "1.2 km",
      travel_walk: "15 min",
      travel_taxi: "4 min (₩4,200)",
      travel_bus: "7 min (Bus #802)",
      recommended_for: ["Couples", "Young fans", "Spicy lovers"],
      recommended_for_kr: ["커플", "청년 팬", "매운맛 러버"],
      hours_en: "11:30 AM - 10:00 PM (Break 3-4:30 PM)",
      hours_kr: "11:30 ~ 22:00 (브레이크타임 15:00~16:30)",
      signature_en: "Spicy Tofu Duruchigi (두부두루치기), Boiled Pork Suyuk (수육), Crispy Jeon (전)",
      signature_kr: "매콤한 두부두루치기, 수육, 바삭한 부추전",
      lat: 36.3245,
      lng: 127.4245,
      address_en: "30-16 Jungang-ro 130beon-gil, Jung-gu, Daejeon",
      address_kr: "대전 중구 중앙로130번길 30-16 (대흥동)",
      image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
      description_en: "The original inventor of Daejeon's iconic Tofu Duruchigi since 1969. Tucked away in a nostalgic retro alleyway in Daeheung-dong, soft freshly made tofu swims in a rich, fiery red pepper sauce.",
      description_kr: "1969년 시작된 대전 두부두루치기의 원조집! 대흥동 옛 골목 정취 속에서 부드러운 손두부와 얼큰한 특제 고춧가루 양념이 어우러져 밥도둑이자 술안주로 최고.",
      tags: ["🌶️ Original 1969", "🏠 Retro Alley", "✨ Soul Food"]
    },
    {
      id: "myeongseong_bbq",
      name_en: "Myeongseong Galbi & Hanwoo",
      name_kr: "명성숯불갈비",
      category: "bbq",
      category_label_en: "Korean Charcoal BBQ",
      category_label_kr: "참숯 돼지갈비 & 삼겹살",
      price: "₩16,000 - ₩32,000",
      rating: 4.8,
      reviews_count: 1420,
      distance_km: "0.6 km",
      travel_walk: "7 min",
      travel_taxi: "2 min (₩3,800)",
      travel_bus: "5 min",
      recommended_for: ["Families", "Groups", "Cheering Squads"],
      recommended_for_kr: ["가족 단체", "직관 동행", "응원단 회식"],
      hours_en: "12:00 PM - 11:30 PM (Daily)",
      hours_kr: "12:00 ~ 23:30 (연중무휴)",
      signature_en: "Charcoal-grilled Sweet Marinated Pork Ribs (돼지갈비), Thick Pork Belly (삼겹살)",
      signature_kr: "수제 양념 돼지갈비, 두툼한 국내산 생삼겹살, 된장찌개",
      lat: 36.3195,
      lng: 127.4265,
      address_en: "18 Hanbat-daero, Jung-gu, Daejeon",
      address_kr: "대전 중구 부사동 (야구장 도보 7분)",
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
      description_en: "Located just a short 7-minute stroll from Eagles Park, this bustling Korean charcoal BBQ joint is the go-to celebratory dinner spot for players and die-hard fans after the final out.",
      description_kr: "이글스파크에서 걸어서 단 7분! 참숯 향이 가득 밴 달콤짭조름한 양념갈비와 육즙 가득한 삼겹살로 승리의 기쁨을 만끽하는 팬들의 단골 명소.",
      tags: ["🍖 Juicy BBQ", "🚶 7 Min Walk", "🍻 Fans Hangout"]
    },
    {
      id: "eagles_chimaek",
      name_en: "Bongmyeong & Stadium Chimaek",
      name_kr: "이글스 치맥 & 수제 가마솥 통닭",
      category: "chicken",
      category_label_en: "Korean Fried Chicken & Beer",
      category_label_kr: "가마솥 통닭 & 시원한 생맥주",
      price: "₩17,000 - ₩23,000",
      rating: 4.9,
      reviews_count: 2200,
      distance_km: "0.2 km",
      travel_walk: "3 min",
      travel_taxi: "1 min",
      travel_bus: "Walk is faster",
      recommended_for: ["Young fans", "Couples", "Beer Lovers"],
      recommended_for_kr: ["젊은 팬", "커플", "치맥러"],
      hours_en: "02:00 PM - 12:00 AM (Game Days)",
      hours_kr: "14:00 ~ 24:00 (경기일 집중 운영)",
      signature_en: "Crispy Traditional Cauldron Whole Chicken, Seasoned Sweet-Spicy Chix, Draft Beer Growler",
      signature_kr: "가마솥 옛날통닭, 바삭 양념반 후라이드반, 테이크아웃 생맥주",
      lat: 36.3168,
      lng: 127.4285,
      address_en: "Directly in front of Eagles Park 1st Base Gate",
      address_kr: "이글스파크 1루 매표소 바로 앞",
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80",
      description_en: "Nothing beats hot crispy fried chicken paired with an icy cold draft beer in your stadium seat while singing the Hanwha Eagles fight song! Order fresh right before gate entry.",
      description_kr: "야구장 직관의 꽃은 바로 치맥! 1루 게이트 바로 앞에서 갓 튀겨 바삭한 가마솥 통닭과 시원한 생맥주를 챙겨 응원석으로 직행하세요!",
      tags: ["🍗 Stadium Essential", "🍺 Cold Draft Beer", "⚡ Fast Pickup"]
    },
    {
      id: "wanggwan",
      name_en: "Wanggwan Sikdang",
      name_kr: "왕관식당",
      category: "casual",
      category_label_en: "Yukhoe & Bean Sprout Rice",
      category_label_kr: "육회 콩나물밥 (하루 2시간 영업)",
      price: "₩7,000 - ₩16,000",
      rating: 4.9,
      reviews_count: 1850,
      distance_km: "1.9 km",
      travel_walk: "25 min",
      travel_taxi: "5 min (₩4,800)",
      travel_bus: "12 min",
      recommended_for: ["Foodies", "Couples", "Early birds"],
      recommended_for_kr: ["미식가", "커플", "점심 방문객"],
      hours_en: "12:00 PM - 02:00 PM Only! (2 Hours Daily)",
      hours_kr: "12:00 ~ 14:00 (하루 딱 2시간만 한정 영업!)",
      signature_en: "Seasoned Fresh Beef Yukhoe (육회), Bean Sprout Rice Bowl (콩나물밥)",
      signature_kr: "한우 육회, 아삭한 콩나물밥, 비법 양념장",
      lat: 36.3312,
      lng: 127.4320,
      address_en: "40-9 Jung-dong, Dong-gu, Daejeon",
      address_kr: "대전 동구 중동 40-9 (대전역 인근)",
      image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80",
      description_en: "Open for just TWO hours each day (12:00-14:00). Freshly seasoned Korean beef yukhoe placed atop steaming bean sprout rice with secret scallion soy sauce creates pure magic.",
      description_kr: "하루 딱 2시간만 문을 여는 전설의 은둔 식당! 아삭한 콩나물밥에 감칠맛 넘치는 한우 육회와 파 양념장을 비벼먹는 천상의 조화.",
      tags: ["⏰ 2hr Only", "🥩 Fresh Beef Yukhoe", "🌟 Rare Gem"]
    },
    {
      id: "jungang_pocha",
      name_en: "Jungang Market Night Pocha Alley",
      name_kr: "중앙시장 야시장 포차거리",
      category: "night",
      category_label_en: "Late-Night Street Food & Drinks",
      category_label_kr: "야시장 포차 & 전통 안주",
      price: "₩5,000 - ₩15,000",
      rating: 4.7,
      reviews_count: 3100,
      distance_km: "1.7 km",
      travel_walk: "22 min",
      travel_taxi: "5 min (₩4,500)",
      travel_bus: "10 min",
      recommended_for: ["Night owls", "Friends", "Post-game cheers"],
      recommended_for_kr: ["친구 모임", "야구 뒤풀이", "포차 감성"],
      hours_en: "06:00 PM - 01:00 AM (Thurs-Sun Night Market)",
      hours_kr: "18:00 ~ 익일 01:00 (목/금/토/일 야시장 활성화)",
      signature_en: "Pajeon Pancakes, Spicy Tteokbokki, Skewers, Makgeolli & Soju",
      signature_kr: "해물파전, 닭발, 모듬튀김, 매운 떡볶이, 대전 생막걸리",
      lat: 36.3285,
      lng: 127.4305,
      address_en: "Jungang Market, Dong-gu, Daejeon",
      address_kr: "대전 동구 중앙시장 야시장 거리",
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
      description_en: "When the final inning ends, win or lose, baseball fans gather under the romantic retro lantern lights of Jungang Market for savory Korean pancakes, sizzling stir-fries, and cheers!",
      description_kr: "경기가 끝난 후 승리의 여운을 나누는 야시장 포차 골목! 지글지글 부쳐내는 해물파전과 매콤한 안주, 시원한 막걸리와 함께하는 최고의 뒤풀이.",
      tags: ["🌙 Night Market", "🍶 Retro Pocha", "🎉 Victory Party"]
    }
  ],

  cafes: [
    {
      id: "sungsimdang_main",
      name_en: "Sung Sim Dang Main Bakery",
      name_kr: "성심당 본점 (성지순례)",
      signature_menu: "Fried Soboro (튀김소보로) & Boochu-bbang (부추빵)",
      signature_menu_kr: "튀김소보로, 판타롱 부추빵, 명란바게트",
      price_range: "₩1,800 - ₩4,000 per bread",
      distance_km: "1.3 km",
      travel_time: "15 min walk / 4 min taxi",
      visit_duration: "30 - 45 min",
      atmosphere: "Vibrant, Iconic, Historic, Bustling",
      atmosphere_kr: "활기찬, 대한민국 대표 빵지순례, 역사적인",
      photo_friendly: true,
      rating: 4.9,
      reviews_count: 18400,
      hours_en: "08:00 AM - 10:00 PM (Daily)",
      hours_kr: "08:00 ~ 22:00 (연중무휴)",
      address_en: "15 Eunhaeng-dong, Jung-gu, Daejeon (Eunhaeng Branch)",
      address_kr: "대전 중구 대종로480번길 15 (은행동)",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
      lat: 36.3275,
      lng: 127.4271,
      description_en: "The crown jewel of Daejeon and Korea's most famous bakery since 1956. The crunch of freshly fried Soboro stuffed with sweet red bean paste and the savory chive Boochu-bbang are legendary.",
      description_kr: "1956년 문을 연 대한민국 No.1 빵지순례 성지! 바삭하고 달콤한 튀김소보로와 감칠맛 가득한 판타롱 부추빵, 짭조름한 명란바게트는 대전 방문 필수 코스!",
      must_buy: ["Fried Soboro Box", "Boochu-bbang", "Myeongran Baguette", "Small Soboro Trio"]
    },
    {
      id: "sungsimdang_boutique",
      name_en: "Sung Sim Dang Cake Boutique",
      name_kr: "성심당 케익부띠끄",
      signature_menu: "Strawberry / Mango Siru Cake (딸기/망고 시루) & Roll Cakes",
      signature_menu_kr: "과일 가득 시루 케이크, 순수롤, 마들렌",
      price_range: "₩3,500 - ₩9,000 (Slices / Desserts)",
      distance_km: "1.2 km",
      travel_time: "14 min walk / 4 min taxi",
      visit_duration: "30 - 40 min",
      atmosphere: "European Classic, Elegant, Sweet, Aesthetic",
      atmosphere_kr: "유럽풍 앤틱, 달콤한, 고급스러운 디저트 살롱",
      photo_friendly: true,
      rating: 4.9,
      reviews_count: 9600,
      hours_en: "08:30 AM - 09:30 PM (Daily)",
      hours_kr: "08:30 ~ 21:30 (연중무휴)",
      address_en: "480 Daejong-ro, Jung-gu, Daejeon",
      address_kr: "대전 중구 대종로 480 (은행동 153)",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
      lat: 36.3270,
      lng: 127.4268,
      description_en: "Dedicated entirely to high-end European cakes, tarts, and the viral Fruit Siru Cakes that weigh over 2 kilograms with fresh seasonal fruits. Right around the corner from the main bakery.",
      description_kr: "SNS를 뜨겁게 달군 2kg 무게의 생과일 시루 케이크와 부드러운 순수롤이 가득한 유럽풍 고급 디저트 부띠끄! 사진 찍기 가장 좋은 핫플레이스.",
      must_buy: ["Seasonal Siru Cake Slices", "Sunsu Roll (Pure Cream Roll)", "Tart Selection"]
    },
    {
      id: "cafe_sosorowa",
      name_en: "Cafe Sosorowa",
      name_kr: "카페 소소로와",
      signature_menu: "Hand-drip Single Origin & Matcha Terrine",
      signature_menu_kr: "싱글오리진 핸드드립, 말차 테린느, 수제 청포도 에이드",
      price_range: "₩5,000 - ₩7,500",
      distance_km: "1.0 km",
      travel_time: "12 min walk / 3 min taxi",
      visit_duration: "45 - 60 min",
      atmosphere: "Peaceful Hanok, Warm Wood, Cozy, Relaxing",
      atmosphere_kr: "고즈넉한 한옥 감성, 따뜻한 우드톤, 힐링 공간",
      photo_friendly: true,
      rating: 4.8,
      reviews_count: 980,
      hours_en: "12:00 PM - 09:00 PM (Closed Tuesdays)",
      hours_kr: "12:00 ~ 21:00 (화요일 휴무)",
      address_en: "14 Daeheung-ro 121beon-gil, Jung-gu, Daejeon",
      address_kr: "대전 중구 대흥로121번길 14 (대흥동)",
      image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
      lat: 36.3235,
      lng: 127.4260,
      description_en: "A serene hidden hanok oasis in Daeheung-dong Cafe Street. Natural sunlight filters through wooden lattice windows, providing a calm respite before the thunderous cheering begins.",
      description_kr: "대흥동 카페거리의 숨겨진 감성 한옥 오아시스. 따스한 햇살과 은은한 나무 향 속에서 정성스런 핸드드립 커피와 디저트를 즐길 수 있는 쉼터.",
      must_buy: ["Signature Einspänner", "Matcha Terrine", "Seasonal Fruit Ade"]
    },
    {
      id: "cafe_interview",
      name_en: "Cafe INTERVIEW",
      name_kr: "커피인터뷰 (궁동 본점)",
      signature_menu: "Coconut Coffee Smoothie & Basque Cheesecake",
      signature_menu_kr: "코코넛 커피 스무디, 바스크 치즈케이크, 아인슈페너",
      price_range: "₩6,000 - ₩8,500",
      distance_km: "7.5 km",
      travel_time: "18 min taxi / 35 min transit",
      visit_duration: "1 - 1.5 hours",
      atmosphere: "Lush Forest Resort, Waterfall Deck, Architectural",
      atmosphere_kr: "도심 속 숲속 리조트, 감성 건축물, 시원한 테라스",
      photo_friendly: true,
      rating: 4.9,
      reviews_count: 4600,
      hours_en: "11:00 AM - 10:00 PM (Daily)",
      hours_kr: "11:00 ~ 22:00 (연중무휴)",
      address_en: "19-8 Hanbat-daero 371beon-gil, Yuseong-gu, Daejeon",
      address_kr: "대전 유성구 한밭대로371번길 19-8 (궁동)",
      image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
      lat: 36.3625,
      lng: 127.3458,
      description_en: "A world-class architectural masterpiece designed like an exotic Southeast Asian forest retreat with wood walkways over babbling streams. Daejeon's top photo-op destination.",
      description_kr: "마치 발리의 울창한 숲속 리조트에 온 듯한 감각적인 건축물과 징검다리 테라스가 매력적인 대전 최고의 인스타 핫플레이스!",
      must_buy: ["Coconut Coffee Smoothie", "Cream Latte", "Basque Burnt Cheesecake"]
    },
    {
      id: "kkumnamu_cafe",
      name_en: "Kkumnamu Cafe & Bakery",
      name_kr: "꿈나무 베이커리 카페",
      signature_menu: "Fresh Croissants & Orange Cream Latte",
      signature_menu_kr: "수제 크루아상, 오렌지 크림 라떼, 에그타르트",
      price_range: "₩4,500 - ₩6,500",
      distance_km: "0.5 km",
      travel_time: "6 min walk",
      visit_duration: "30 - 45 min",
      atmosphere: "Family friendly, Warm, Baseball Neighbor",
      atmosphere_kr: "가족 친화적인, 아늑한 야구장 이웃 카페",
      photo_friendly: true,
      rating: 4.7,
      reviews_count: 650,
      hours_en: "10:00 AM - 09:00 PM (Tues-Sun)",
      hours_kr: "10:00 ~ 21:00 (월요일 휴무)",
      address_en: "Busa-dong, Jung-gu (Near Eagles Park Gate)",
      address_kr: "대전 중구 부사동 (이글스파크 도보 6분)",
      image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
      lat: 36.3185,
      lng: 127.4310,
      description_en: "Super cozy neighborhood bakery cafe just 6 minutes walk from the stadium. Known for butter-rich croissants and refreshing orange citrus coffees in Hanwha team colors!",
      description_kr: "야구장에서 걸어서 6분 거리! 버터 풍미 가득한 갓 구운 크루아상과 한화이글스 오렌지 컬러의 시그니처 크림라떼가 매력적인 아담한 힐링 카페.",
      must_buy: ["Orange Cream Latte", "Almond Croissant", "Egg Tart Trio"]
    }
  ],

  attractions: [
    {
      id: "skyroad",
      name_en: "Eunhaeng-dong Skyroad & Culture Street",
      name_kr: "으능정이 문화의거리 & 스카이로드",
      filter_tag: "nearby",
      filter_tag_kr: "가까운 명소",
      why_visit_en: "Vibrant pedestrian mall covered by a colossal 214-meter long LED canopy screen, bustling with youth fashion, arcade games, and street food.",
      why_visit_kr: "길이 214m, 높이 20m의 웅장한 LED 캐노피 '스카이로드'와 젊음의 패션·놀거리·길거리 음식이 가득한 대전 대표 문화의 거리.",
      duration: "1 - 1.5 hours",
      distance_km: "1.3 km",
      travel_walk: "16 min",
      travel_transit: "4 min taxi / 7 min bus (#802)",
      family_friendly: true,
      photo_spot: true,
      rainy_friendly: true,
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      lat: 36.3278,
      lng: 127.4275,
      tips_en: "Best visited in the evening when the LED canopy comes alive with interactive animations and games!",
      tips_kr: "저녁 시간에 방문하면 LED 천장에서 펼쳐지는 화려한 미디어아트와 스마트폰 연동 게임을 즐길 수 있습니다!"
    },
    {
      id: "bomunsan",
      name_en: "Bomunsan Mountain Park & Observatory",
      name_kr: "보문산 공원 & 보문산성 전망대",
      filter_tag: "nearby",
      filter_tag_kr: "가까운 명소",
      why_visit_en: "Towering right behind Eagles Park, Bomunsan offers a crisp forest walk, cable car history, and breathtaking panoramic sunset views over the stadium and Daejeon skyline.",
      why_visit_kr: "이글스파크 바로 뒤편에 위치한 대전의 진산! 완만한 산책로와 전망대에서 시원한 대전 시내 전경과 붉게 물드는 노을을 감상할 수 있습니다.",
      duration: "1 - 2 hours",
      distance_km: "1.5 km",
      travel_walk: "20 min hike",
      travel_transit: "6 min taxi (₩4,500)",
      family_friendly: true,
      photo_spot: true,
      rainy_friendly: false,
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
      lat: 36.3075,
      lng: 127.4215,
      tips_en: "Look down during sunset to see the stadium floodlights glowing like a beacon of baseball passion.",
      tips_kr: "노을 무렵 전망대에 오르면 야구장의 밝은 조명이 켜지는 장관을 한눈에 내려다볼 수 있습니다."
    },
    {
      id: "hanbit_tower",
      name_en: "Expo Science Park & Hanbit Tower",
      name_kr: "엑스포 과학공원 & 한빛탑 미디어파사드",
      filter_tag: "photo",
      filter_tag_kr: "포토스팟",
      why_visit_en: "The iconic symbol of 'Science City Daejeon' from the 1993 World Expo, featuring an 18-story spaceship tower, synchronized music fountain, and night light festivals.",
      why_visit_kr: "1993 대전 엑스포의 상징이자 과학도시 대전의 랜드마크! 93m 높이의 우주선 모양 한빛탑과 환상적인 음악분수, 미디어파사드가 펼쳐집니다.",
      duration: "1.5 - 2 hours",
      distance_km: "6.8 km",
      travel_walk: "Too far to walk",
      travel_transit: "15 min taxi (₩8,500) / 30 min Bus #705",
      family_friendly: true,
      photo_spot: true,
      rainy_friendly: true,
      image: "https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80",
      lat: 36.3762,
      lng: 127.3882,
      tips_en: "The musical fountain show runs every evening from 7 PM to 9 PM (free admission).",
      tips_kr: "매일 저녁 19시~21시 음악에 맞춰 춤추는 분수 쇼와 화려한 레이저 쇼가 무료로 펼쳐집니다."
    },
    {
      id: "ppuri_park",
      name_en: "PPuri Park (Genealogy & River Park)",
      name_kr: "뿌리공원 (효 문화 테마공원)",
      filter_tag: "family",
      filter_tag_kr: "가족/휴식",
      why_visit_en: "A scenic riverfront park with Korean family clan sculptures, a suspension bridge, pedal swan boats, and lush waterside boardwalks surrounded by cliffs.",
      why_visit_kr: "유유히 흐르는 유등천과 기암절벽을 배경으로 만성교 출렁다리, 오리배, 244개 가문 조형물이 어우러진 평화로운 힐링 수변 공원.",
      duration: "1.5 - 2.5 hours",
      distance_km: "4.2 km",
      travel_walk: "Too far to walk",
      travel_transit: "10 min taxi (₩6,000) / 20 min Bus #311",
      family_friendly: true,
      photo_spot: true,
      rainy_friendly: false,
      image: "https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=800&q=80",
      lat: 36.2862,
      lng: 127.3880,
      tips_en: "Cross the rainbow-lit Mansunggyo Suspension Bridge at dusk for magical river reflection photos.",
      tips_kr: "해질녘 무지개빛 조명이 들어오는 만성교 출렁다리를 건너며 남기는 수변 사진이 일품입니다."
    },
    {
      id: "modern_history",
      name_en: "Daejeon Modern History Exhibition Hall",
      name_kr: "대전근현대사전시관 (구 충남도청사)",
      filter_tag: "rainy",
      filter_tag_kr: "실내/역사",
      why_visit_en: "A striking 1932 modern heritage building featured in numerous K-dramas and films, showcasing Daejeon's rapid growth from a small railway junction to a metropolis.",
      why_visit_kr: "1932년 건립된 고풍스러운 근대 문화유산 건축물(각종 영화/드라마 촬영지). 대전의 철도 역사와 발전사를 품은 실내 힐링 명소.",
      duration: "45 - 60 min",
      distance_km: "1.6 km",
      travel_walk: "20 min",
      travel_transit: "5 min taxi / 9 min transit",
      family_friendly: true,
      photo_spot: true,
      rainy_friendly: true,
      image: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&w=800&q=80",
      lat: 36.3260,
      lng: 127.4205,
      tips_en: "Free admission and air-conditioned; perfect for sunny hot afternoons or rainy game days.",
      tips_kr: "입장료 무료 및 쾌적한 실내 공간으로, 경기 전 무더위나 우천 시 여유롭게 둘러보기 좋습니다."
    },
    {
      id: "oworlld",
      name_en: "Daejeon O-World Theme Park & Zoo",
      name_kr: "대전 오월드 (동물원 & 플라워랜드)",
      filter_tag: "family",
      filter_tag_kr: "가족 추천",
      why_visit_en: "Central Korea's premier amusement park combining African safari zoo, flower gardens, thrill rides, and nighttime fantasy light festivals.",
      why_visit_kr: "사파리 동물원, 놀이기구, 플라워랜드, 버드랜드가 결합된 중부권 최대 테마파크로 아이를 동반한 가족 팬들에게 최고의 만족을 선사합니다.",
      duration: "3 - 4 hours",
      distance_km: "5.5 km",
      travel_walk: "Too far to walk",
      travel_transit: "12 min taxi (₩7,500) / 25 min Bus #311 or #115",
      family_friendly: true,
      photo_spot: true,
      rainy_friendly: false,
      image: "https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?auto=format&fit=crop&w=800&q=80",
      lat: 36.2890,
      lng: 127.3965,
      tips_en: "Arrive in the morning before heading to the late afternoon baseball game!",
      tips_kr: "오전 일찍 방문하여 사파리와 놀이시설을 즐긴 후, 오후 4시경 야구장으로 이동하는 일정을 추천합니다."
    }
  ],

  transportation: {
    origin: "Daejeon Station (KTX / SRT / Subway Line 1)",
    origin_kr: "KTX 대전역 (경부선 / 도시철도 1호선)",
    destination: "Hanwha Life Eagles Park",
    destination_kr: "한화생명 이글스파크",
    total_distance: "2.4 km",
    options: [
      {
        id: "taxi",
        icon: "🚕",
        mode_en: "TAXI",
        mode_kr: "택시",
        travel_time_en: "8 – 10 min",
        travel_time_kr: "약 8~10분",
        cost_en: "₩5,000 – ₩5,800",
        cost_kr: "약 5,000원 ~ 5,800원",
        convenience: 5,
        recommended_for_en: "Groups of 2-4, Families, Traveling with luggage, Fast arrival",
        recommended_for_kr: "2~4인 동행, 짐이 많은 경우, 빠른 도착 원할 때",
        pickup_guide_en: "Exit Daejeon Station West Square (Exit 1), follow taxi rank signs. Say 'Hanwha Eagles Park' (이글스파크 가주세요).",
        pickup_guide_kr: "대전역 서광장 1번 출구 앞 택시 승강장 이용. '한밭종합운동장 이글스파크' 말씀하시면 정문 바로 하차."
      },
      {
        id: "bus",
        icon: "🚌",
        mode_en: "DIRECT CITY BUS",
        mode_kr: "시내버스 (직통)",
        travel_time_en: "15 – 18 min",
        travel_time_kr: "약 15~18분",
        cost_en: "₩1,500 (Transit card)",
        cost_kr: "1,500원 (교통카드)",
        convenience: 4,
        recommended_for_en: "Solo fans, Budget travelers, Authentic local atmosphere",
        recommended_for_kr: "나홀로 직관러, 대중교통 선호자, 알뜰 여행",
        bus_numbers: ["#802 (Direct to Stadium)", "#2", "#52", "#108"],
        bus_numbers_kr: ["802번 (야구장 정문 직통)", "2번", "52번", "108번"],
        pickup_guide_en: "Board Bus #802 at Daejeon Station West Square Stop. Get off at 'Hanwha Life Eagles Park' stop (5 stops).",
        pickup_guide_kr: "대전역 서광장 버스정류장에서 802번 탑승 → 5개 정류장 후 '한화생명이글스파크' 정류장 하차 바로 앞."
      },
      {
        id: "walking",
        icon: "🚶",
        mode_en: "SCENIC CITY WALK",
        mode_kr: "도보 산책 코스",
        travel_time_en: "32 – 38 min",
        travel_time_kr: "약 32~38분",
        cost_en: "Free (0 kcal burn!)",
        cost_kr: "무료 (약 2.4km 산책)",
        convenience: 3,
        recommended_for_en: "Couples, Street photographers, Exploring local markets on foot",
        recommended_for_kr: "거리 구경 좋아하는 팬, 중앙시장 & 으능정이 거리 경유자",
        route_stops_en: "Daejeon Station → Jungang Market Alley → Eunhaeng-dong Skyroad → Daeheung Cafe Street → Eagles Park",
        route_stops_kr: "대전역 → 중앙시장 먹자골목 → 으능정이 스카이로드 → 대흥동 카페거리 → 이글스파크",
        pickup_guide_en: "Walk straight out Exit 1 across Mokcheokgyo Bridge. Enjoy street food along the way.",
        pickup_guide_kr: "대전역 1번 출구에서 목척교를 건너 대종로를 따라 직진. 성심당과 대흥동 맛집들을 들르며 천천히 걷기 좋습니다."
      },
      {
        id: "transit",
        icon: "🚇",
        mode_en: "METRO + SHORT WALK",
        mode_kr: "지하철 + 도보/환승",
        travel_time_en: "18 – 22 min",
        travel_time_kr: "약 18~22분",
        cost_en: "₩1,550",
        cost_kr: "1,550원 (환승 할인)",
        convenience: 4,
        recommended_for_en: "Avoiding game-day road congestion during peak weekend hours",
        recommended_for_kr: "주말 피크타임 도로 정체 피하고 싶을 때",
        pickup_guide_en: "Daejeon Metro Line 1 (Daejeon Station → Jungangno Station, 1 stop). Walk 12 min or transfer to Bus #802.",
        pickup_guide_kr: "대전 도시철도 1호선 탑승 (대전역 → 중앙로역, 1개역 이동). 중앙로역 3번 출구에서 도보 또는 802번 환승."
      }
    ],
    game_day_tips_en: [
      "⚠️ Weekend game days have heavy traffic around Busa-dong intersection 1 hour before first pitch. Leave early!",
      "🅿️ Stadium parking fills up 2 hours before the game. We strongly recommend public transportation or Munchang-dong public lot.",
      "🧳 Luggage lockers are located on the 2nd floor of KTX Daejeon Station and next to the 1st base ticket office."
    ],
    game_day_tips_kr: [
      "⚠️ 주말 경기일은 경기 시작 1시간 전부터 부사오거리 일대 교통이 혼잡하므로 여유있게 이동하세요.",
      "🅿️ 구장 내 주차장은 경기 시작 2시간 전 조기 만차됩니다. 대중교통 또는 문창동 공영주차장 이용을 적극 권장합니다.",
      "🧳 짐 보관함은 KTX 대전역 2층 대합실 및 이글스파크 1루 매표소 옆 물품보관함을 이용하실 수 있습니다."
    ]
  },

  itineraries: [
    {
      id: "young_trendy",
      title_en: "YOUNG & TRENDY",
      title_kr: "청춘 & 트렌디 직관 코스",
      tagline_en: "Aesthetic Hanok Cafe → Spicy Duruchigi → Cheer Zone → Night Craft Beer",
      tagline_kr: "대흥동 감성 카페 → 매콤 두루치기 → 1루 열광응원 → 뒤풀이 수제맥주",
      badge_en: "🔥 Most Popular with Friends & Couples",
      badge_kr: "🔥 2030 팬 & 커플 선호도 1위",
      color: "from-orange-500 to-amber-600",
      total_time: "Approx. 7 Hours",
      steps: [
        { time: "01:30 PM", title_en: "Arrive KTX Daejeon Station", title_kr: "KTX 대전역 도착 & 짐 보관", desc_en: "Drop heavy bags in station lockers and take a 5 min taxi to Daeheung-dong.", desc_kr: "대전역 물품보관함에 짐을 맡기고 택시로 대흥동으로 이동", icon: "🚉" },
        { time: "02:00 PM", title_en: "Cafe Sosorowa Hanok Break", title_kr: "카페 소소로와 감성 타임", desc_en: "Sip iced hand-drip coffee and snap photos in tranquil Hanok courtyard.", desc_kr: "고즈넉한 한옥에서 시그니처 아인슈페너와 디저트 즐기기", icon: "☕" },
        { time: "03:30 PM", title_en: "Fiery Gwangcheon Sikdang", title_kr: "광천식당 오징어 두루치기", desc_en: "Fuel up with legendary spicy squid duruchigi & extra noodles.", desc_kr: "중독성 넘치는 매운맛으로 경기 전 텐션 충전!", icon: "🍚" },
        { time: "05:00 PM", title_en: "Eagles Park 1st Base Cheer Zone", title_kr: "이글스파크 1루 응원석 입장", desc_en: "Wear orange jerseys, pick up cheering sticks, get stadium chicken!", desc_kr: "주황색 유니폼 착용, 응원봉 흔들며 육성응원 만끽", icon: "⚾" },
        { time: "09:30 PM", title_en: "Post-Game Victory Craft Beer", title_kr: "승리의 수제맥주 & 치킨 뒤풀이", desc_en: "Celebrate the home run at lively Daeheung-dong pub street.", desc_kr: "대흥동 펍 거리에서 팬들과 하이파이브하며 뒤풀이", icon: "🍻" }
      ]
    },
    {
      id: "family_day",
      title_en: "FAMILY DAY",
      title_kr: "온 가족 해피 이글스 데이",
      tagline_en: "Science Museum / Zoo → Sweet Bulgogi Feast → Grass Picnic Zone",
      tagline_kr: "국립중앙과학관/오월드 → 숯불 꿀갈비 → 외야 잔디 피크닉존",
      badge_en: "👨‍👩‍👧 Perfect for Kids & Parents",
      badge_kr: "👨‍👩‍👧 아이와 부모님 모두 만족",
      color: "from-blue-600 to-indigo-700",
      total_time: "Approx. 8 Hours",
      steps: [
        { time: "11:00 AM", title_en: "Daejeon O-World or Science Park", title_kr: "대전 오월드 동물원 or 엑스포 과학공원", desc_en: "Safari adventure and hands-on science exhibits that kids love.", desc_kr: "어린이들이 좋아하는 사파리 투어와 신나는 체험 활동", icon: "🦁" },
        { time: "02:00 PM", title_en: "Myeongseong Charcoal Pork Galbi", title_kr: "명성 숯불 돼지갈비 맛있는 점심", desc_en: "Tender, sweet charcoal BBQ and cooling bibim naengmyeon.", desc_kr: "부드럽고 달콤한 양념갈비로 온 가족 푸짐한 식사", icon: "🍖" },
        { time: "03:45 PM", title_en: "Kkumnamu Bakery Cafe Snack Stop", title_kr: "꿈나무 카페 디저트 & 주스", desc_en: "Fresh croissants and fruit juices just 6 min from the stadium.", desc_kr: "야구장 바로 옆 아늑한 카페에서 음료와 빵 테이크아웃", icon: "🥐" },
        { time: "04:45 PM", title_en: "Outfield Picnic Mat Seating", title_kr: "외야 잔디석 피크닉 & 패밀리 직관", desc_en: "Spread a picnic mat, eat stadium tteokbokki, watch home runs fly!", desc_kr: "돗자리 펴고 편안하게 간식 먹으며 야구 경기 관람", icon: "🏟️" }
      ]
    },
    {
      id: "foodie_day",
      title_en: "FOODIE DAY",
      title_kr: "미식 탐방 & 빵지순례 코스",
      tagline_en: "60yr Shindo Kalguksu → Sung Sim Dang Siru Cake → Stadium Fried Chicken",
      tagline_kr: "60년 전통 신도칼국수 → 성심당 시루케이크 빵지순례 → 구장 치맥",
      badge_en: "🍜 Daejeon Gourmet Masters",
      badge_kr: "🍜 대전 3대 명물 정복",
      color: "from-emerald-600 to-teal-700",
      total_time: "Approx. 6.5 Hours",
      steps: [
        { time: "12:00 PM", title_en: "Wanggwan Sikdang Yukhoe Rice (12-2 PM)", title_kr: "왕관식당 육회 콩나물밥 (점심 한정)", desc_en: "Taste the legendary 2-hour daily fresh seasoned beef bowl.", desc_kr: "하루 딱 2시간 문 여는 은둔 고수의 육회 콩나물밥", icon: "🥩" },
        { time: "01:30 PM", title_en: "Sung Sim Dang Main & Boutique Run", title_kr: "성심당 본점 & 케익부띠끄 빵지순례", desc_en: "Grab hot Fried Soboro boxes and sweet mango/strawberry tarts.", desc_kr: "갓 튀긴 튀김소보로 박스와 부추빵, 명란바게트 쇼핑", icon: "🥐" },
        { time: "03:30 PM", title_en: "Shindo Kalguksu Warm Broth", title_kr: "신도칼국수 고소한 들깨칼국수", desc_en: "Deep savory broth that cleanses the palate before game rush.", desc_kr: "깊고 구수한 들깨 육수로 속을 든든하게 채우기", icon: "🍜" },
        { time: "05:00 PM", title_en: "Stadium Chimaek + Bori Tteokbokki", title_kr: "구장 보리떡볶이 & 바삭 가마솥 통닭", desc_en: "The ultimate stadium gourmet feast while rooting for Eagles.", desc_kr: "이글스파크 대표 명물 떡볶이와 가마솥 통닭으로 직관 완성", icon: "🍗" }
      ]
    },
    {
      id: "relaxing_day",
      title_en: "RELAXING DAY",
      title_kr: "힐링 숲길 & 슬로우 트래블",
      tagline_en: "Bomunsan Forest Lookout → Quiet Tearoom → Modern Heritage → Sunset Baseball",
      tagline_kr: "보문산 숲길 산책 → 고즈넉 찻집 → 근현대사 전시관 → 노을빛 야구장",
      badge_en: "🌿 Nature & Peaceful City Vibe",
      badge_kr: "🌿 여유롭고 편안한 힐링",
      color: "from-amber-600 to-rose-700",
      total_time: "Approx. 6 Hours",
      steps: [
        { time: "01:00 PM", title_en: "Bomunsan Mountain Observatory Walk", title_kr: "보문산 전망대 피톤치드 산책", desc_en: "Breathe fresh pine air and overlook the beautiful stadium panorama.", desc_kr: "야구장 뒤편 숲길 산책과 대전 시내 파노라마 감상", icon: "🌲" },
        { time: "02:45 PM", title_en: "Daejeon Modern Heritage Hall", title_kr: "대전 근현대사 전시관 고풍 관람", desc_en: "Stroll 1930s European-style stone corridors and garden paths.", desc_kr: "영화 촬영지로 유명한 1930년대 고풍스러운 건축물 산책", icon: "🏛️" },
        { time: "04:00 PM", title_en: "Quiet Daeheung Cafe Tea Break", title_kr: "대흥동 아늑한 카페 티 타임", desc_en: "Enjoy cold peach oolong tea and artisanal Basque cheesecake.", desc_kr: "조용하고 감성적인 공간에서 커피 한잔의 여유", icon: "☕" },
        { time: "05:15 PM", title_en: "Sunset Game at Eagles Park", title_kr: "노을 지는 이글스파크 여유로운 직관", desc_en: "Take in the warm orange sunset and the electric crowd excitement.", desc_kr: "붉게 물드는 하늘 아래 시원한 바람 맞으며 야구 감상", icon: "⚾" }
      ]
    }
  ],

  radius_places: {
    "5min": [
      { name_en: "Official Eagles Merchandise Shop", name_kr: "한화이글스 공식 상품샵 (어센틱 샵)", type: "shop", desc_en: "Authentic jerseys, caps, cheering sticks, and mascot dolls.", desc_kr: "공식 유니폼, 모자, 응원봉, 수리 캐릭터 굿즈", time_walk: "1 min walk", icon: "🧢" },
      { name_en: "Bori Tteokbokki & Snack Alley", name_kr: "보리떡볶이 & 야구장 먹거리 골목", type: "food", desc_en: "Famous stadium snacks, skewers, fish cakes, and fried chicken.", desc_kr: "야구팬 필수 성지! 매콤한 떡볶이와 닭강정", time_walk: "2 min walk", icon: "🍢" },
      { name_en: "Kkumnamu Bakery Cafe", name_kr: "꿈나무 베이커리 카페", type: "cafe", desc_en: "Cozy croissant and cold orange latte spot.", desc_kr: "야구장 바로 옆 수제 크루아상 카페", time_walk: "5 min walk", icon: "☕" },
      { name_en: "Myeongseong Charcoal BBQ", name_kr: "명성숯불갈비", type: "food", desc_en: "Juicy pork galbi and samgyeopsal BBQ dinner.", desc_kr: "야구 직관 전후 든든한 참숯 고기구이", time_walk: "5 min walk", icon: "🍖" }
    ],
    "10min": [
      { name_en: "Daeheung-dong Cafe Street", name_kr: "대흥동 카페거리", type: "cafe", desc_en: "Hip aesthetic coffee shops, art galleries, and bakeries.", desc_kr: "감성 카페와 빈티지 갤러리가 모인 핫플레이스", time_walk: "10 min walk", icon: "☕" },
      { name_en: "Jinro-jip Tofu Duruchigi (1969)", name_kr: "진로집 (원조 두부두루치기)", type: "food", desc_en: "50-year heritage spicy tofu in nostalgic alley.", desc_kr: "50년 전통의 칼칼한 손두부 두루치기", time_walk: "12 min walk / 3 min taxi", icon: "🍚" },
      { name_en: "Bomunsan Mountain Base Trail", name_kr: "보문산 숲속 산책로 입구", type: "nature", desc_en: "Lush green pine trails and historic cable car plaza.", desc_kr: "피톤치드 가득한 숲길과 케이블카 광장", time_walk: "10 min walk", icon: "🌲" }
    ],
    "15min": [
      { name_en: "Sung Sim Dang Main Bakery & Cake Boutique", name_kr: "성심당 본점 & 케익부띠끄", type: "bakery", desc_en: "Korea's #1 legendary bakery with fried soboro & fruit cakes.", desc_kr: "대한민국 최고 빵집! 튀김소보로 & 순수롤", time_walk: "15 min walk / 4 min taxi", icon: "🥐" },
      { name_en: "Eunhaeng-dong Skyroad & Culture Mall", name_kr: "으능정이 스카이로드 문화거리", type: "spot", desc_en: "Gigantic 214m LED sky screen and youth shopping avenue.", desc_kr: "214m 초대형 LED 캐노피와 쇼핑 거리", time_walk: "16 min walk / 4 min taxi", icon: "📸" },
      { name_en: "Gwangcheon Sikdang", name_kr: "광천식당 오징어두루치기", type: "food", desc_en: "Fiery spicy squid duruchigi & noodles.", desc_kr: "백종원 3대천왕 오징어 두루치기", time_walk: "16 min walk / 4 min taxi", icon: "🔥" }
    ],
    "20min": [
      { name_en: "Daejeon KTX Station", name_kr: "KTX 대전역", type: "station", desc_en: "High-speed rail hub connecting Seoul, Busan, Daegu.", desc_kr: "서울/부산/동대구 연결 KTX 고속철도역", time_walk: "25 min walk / 8 min taxi", icon: "🚉" },
      { name_en: "Jungang Market Night Pocha", name_kr: "중앙시장 전통 야시장", type: "night", desc_en: "Bustling night market with seafood pancakes and soju.", desc_kr: "야간 포차와 전골, 파전이 있는 전통시장", time_walk: "20 min walk / 5 min taxi", icon: "🌙" },
      { name_en: "Bomunsan Fortress Observatory", name_kr: "보문산성 최고 전망대", type: "view", desc_en: "Top panorama over Daejeon city lights.", desc_kr: "대전 도심 야경이 한눈에 보이는 전망대", time_walk: "25 min hike / 7 min taxi", icon: "🗼" }
    ]
  },

  cheer_guide: {
    title_en: "Hanwha Eagles Cheering & Stadium Culture",
    title_kr: "한화 이글스 응원 문화 & 구장 직관 가이드",
    songs: [
      {
        title_en: "Iconic Chant: 'I Cannot Help Loving You' (나는 행복합니다)",
        title_kr: "대표 응원가: '나는 행복합니다'",
        lyrics_kr: "나는 행복합니다~ 나는 행복합니다~ 나는 행복합니다~ 이글스라 행복합니다!",
        lyrics_en: "I am happy~ I am happy~ I am happy~ I am happy because I am an Eagle!",
        moment: "Sung together when the Eagles score or rally!"
      },
      {
        title_en: "Fight Song: 'Forever Hanwha Eagles' (영원한 한화이글스)",
        title_kr: "구단 공식 응원가: '영원한 한화이글스'",
        lyrics_kr: "승리를 향해 날아올라라~ 최강 한화! 워어어어~ 날려버려라 홈런!",
        lyrics_en: "Soar high toward victory~ The Mightiest Hanwha! Whoaaa~ Blast a Home Run!",
        moment: "Batter walk-up and 8th inning rally time"
      }
    ],
    tips: [
      { icon: "🧡", title_en: "Wear Orange or White", title_kr: "오렌지 & 화이트 드레스코드", desc_en: "The stands are a sea of orange. Pick up an authentic Eagles jersey at the shop!", desc_kr: "1루 응원석은 주황빛 물결! 구장 샵에서 오렌지 유니폼을 챙기세요." },
      { icon: "🥁", title_en: "1st Base is the Cheering Hotspot", title_kr: "1루 오렌지 응원존", desc_en: "Blocks 101-106 are where the cheerleaders and brass band ignite the crowd.", desc_kr: "응원단장과 치어리더의 열정적인 리드를 따라 함께 소리쳐보세요." },
      { icon: "🍗", title_en: "Order In-Seat Food Early", title_kr: "간식 사전 주문 & 포장 팁", desc_en: "Buy famous Bori-tteokbokki and fried chicken 40 min before game start to avoid lines.", desc_kr: "보리떡볶이와 치킨은 경기 시작 40분 전 미리 구매하면 대기 없이 편합니다." }
    ]
  }
};

window.APP_DATA = APP_DATA;
